# Generated by Django 4.2.11 on 2024-05-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_test_description2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
